### ISSUE TITLE
🩺 Improve monitoring for EKS Cluster

### ISSUE THREAD

**Issue by wanieldilson** [ministryofjustice/staff-infrastructure-monitoring-deployments#112]
### User Story

As a member of the CloudOps 
I need to be alerted when there are errors within pods on the k8s cluster
So that our cluster is resilient and maintained properly

### Value / Purpose

More resiliency within the IMA solution.  "Monitoring the monitoring".

### Additional Information

https://github.com/kubernetes/kube-state-metrics is probably a good place to start.

A logging solution is probably necessary too.

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by Gary-H9** [comment]
[This](https://medium.com/@dotdc/a-set-of-modern-grafana-dashboards-for-kubernetes-4b989c72a4b2) article is worth looking at in relation to this work.
