### ISSUE TITLE
Security Groups - Unrestricted Access

### ISSUE THREAD

**Issue by mTouhid** [ministryofjustice/staff-infrastructure-monitoring-deployments#77]
Several security groups have unrestricted access.

- [ ] [thanos-receiver-service](https://github.com/ministryofjustice/staff-infrastructure-monitoring-deployments/blob/main/kubernetes/infrastructure-monitoring/templates/thanos-receiver-service.yaml)
- [ ] [thanos-querier-service](https://github.com/ministryofjustice/staff-infrastructure-monitoring-deployments/blob/main/kubernetes/infrastructure-monitoring/templates/thanos-querier-service.yaml)
- [ ] [alertmanager-service](https://github.com/ministryofjustice/staff-infrastructure-monitoring-deployments/blob/main/kubernetes/infrastructure-monitoring/templates/alertmanager-service.yaml) 

- [ ] Update Trusted Advisor  

According to AWS security advisory, these security groups need better IP restrictions.

**Comment by Gary-H9** [comment]
All three of the above SGs refer to an internal AWS LB and allow traffic inbound from 0.0.0.0/0. Since these are internal the risk would appear to be low but can these be locked down further?
