### ISSUE TITLE
🔐  Enabling Thanos reciever to accept metrics over https

### ISSUE THREAD

**Issue by wanieldilson** [ministryofjustice/staff-infrastructure-monitoring-deployments#78]
## User Story

As a member of the ALZ team
I want to securely remote write metrics to the IMA platform
So I can take advantage of Grafana for visualisation, and have my metrics stored long term

## Value / Purpose

To allow members of the ALZ team to send metrics securely over the internet to our IMA platform

## Useful Contacts

Agoney

## Additional Information

https://prometheus.io/docs/practices/remote_write/

## Definition of Done (DoD)

ALZ team can view their metrics in CloudOps Grafana

**Comment by wanieldilson** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/staff-infrastructure-monitoring-deployments/78?planning-poker) with ZenHub @ASTRobinson @bagg3rs @Gary-H9 @kyphutruong @mitchdawson1982 @mTouhid @moontune

**Comment by bagg3rs** [comment]
🎉 successful remote write! 
`prometheus_1 | ts=2022-04-11T15:54:46.266Z caller=dedupe.go:112 component=remote level=info remote_name=c1eeb0 url=https://remoteURL/api/v1/receive msg="Done replaying WAL" duration=8.2154608s`
